services:
  - type: web
    name: av-file-to-link-pro
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    startCommand: python bot.py
    envVars:
      - key: PORT
        value: 8080
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_USERNAME
        sync: false
      - key: ADMINS
        sync: false
      - key: DATABASE_URI
        sync: false
      - key: BIN_CHANNEL
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: URL
        sync: false
        
